CREATE TABLE `schedule` (
  `schedule_id` varchar(255) NOT NULL,
  `staff_id` varchar(255) DEFAULT NULL,
  `resource_id` varchar(255) DEFAULT NULL,
  `service_id` varchar(255) DEFAULT NULL,
  `monday_start` datetime NOT NULL,
  `tuesday_start` datetime NOT NULL,
  `wedday_start` datetime NOT NULL,
  `thursday_start` datetime NOT NULL,
  `friday_start` datetime NOT NULL,
  `saturday_start` datetime NOT NULL,
  `sunday_start` datetime NOT NULL,
  `monday_end` datetime NOT NULL,
  `tuesday_end` datetime NOT NULL,
  `wedday_end` datetime NOT NULL,
  `thursday_end` datetime NOT NULL,
  `friday_end` datetime NOT NULL,
  `saturday_end` datetime NOT NULL,
  `sunday_end` datetime NOT NULL,
  `create_admin` varchar(255) NOT NULL DEFAULT '0',
  `update_admin` varchar(255) DEFAULT NULL,
  `create_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_ts` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`schedule_id`),
  KEY `staff_id` (`staff_id`),
  KEY `resource_id` (`resource_id`),
  KEY `service_id` (`service_id`),
  CONSTRAINT `schedule_ibfk_1` FOREIGN KEY (`staff_id`) REFERENCES `staff` (`staff_id`),
  CONSTRAINT `schedule_ibfk_2` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`resource_id`),
  CONSTRAINT `schedule_ibfk_3` FOREIGN KEY (`service_id`) REFERENCES `service` (`service_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
