CREATE TABLE `appointment` (
  `appointment_id` int(8) NOT NULL,
  `service_id` varchar(255) DEFAULT NULL,
  `customer_id` varchar(255) NOT NULL,
  `promotion_id` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `is_repeated` tinyint(1) DEFAULT NULL,
  `staff_id` varchar(255) DEFAULT NULL,
  `resources` varchar(255) DEFAULT NULL,
  `status_code` varchar(255) DEFAULT NULL,
  `check_in` datetime DEFAULT NULL,
  `scheduled_at` datetime DEFAULT NULL,
  `create_admin` varchar(255) NOT NULL DEFAULT '0',scs
  `update_admin` varchar(255) DEFAULT NULL,
  `create_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_ts` datetime DEsFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`appointment_id`),
  KEY `service_id` (`service_id`),
  KEY `customer_id` (`customer_id`),
  KEY `promotion_id` (`promotion_id`),
  KEY `staff_id` (`staff_id`),
  KEY `status_code` (`status_code`),
  CONSTRAINT `appointment_ibfk_1` FOREIGN KEY (`service_id`) REFERENCES `service` (`service_id`),
  CONSTRAINT `appointment_ibfk_2` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`customer_id`),
  CONSTRAINT `appointment_ibfk_3` FOREIGN KEY (`promotion_id`) REFERENCES `promotion` (`promotion_id`),
  CONSTRAINT `appointment_ibfk_4` FOREIGN KEY (`staff_id`) REFERENCES `staff` (`staff_id`),
  CONSTRAINT `appointment_ibfk_5` FOREIGN KEY (`status_code`) REFERENCES `status` (`status_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
